import { expect, test, type Page } from "@playwright/test";

async function login(page: Page) {
  await page.goto("/login");
  await page.getByRole("button", { name: "로그인", exact: true }).click();
  await expect(page).toHaveURL(/\/dashboard$/);
  await page.goto("/hr/employee");
  await expect(page.getByRole("grid")).toContainText("김서준");
}
const nameCell = (page: Page) => page.locator('.ag-center-cols-container [row-index="0"] [col-id="display_name"]');
const firstCheck = (page: Page) => page.locator('.ag-pinned-left-cols-container [row-index="0"] .ag-selection-checkbox input');

test("employee work surface preserves edit/save/delete and makes actions explicit", async ({ page, request }) => {
  await request.post("http://127.0.0.1:3101/__scenario", { data: { scenario: "employee-ux" } });
  await login(page);
  await page.getByRole("button", { name: "상세 검색", exact: true }).click();
  await page.getByRole("button", { name: "직책 전체", exact: true }).click();
  await page.getByRole("button", { name: "팀장", exact: true }).click();
  await page.keyboard.press("Escape");
  await page.getByRole("button", { name: "조회", exact: true }).click();
  await expect(page.locator('.ag-center-cols-container [role="row"]')).toHaveCount(1);
  await page.getByRole("button", { name: "조건 초기화", exact: true }).click();
  await expect(page.locator('.ag-center-cols-container [role="row"]')).toHaveCount(3);
  await page.getByRole("button", { name: "상세 검색", exact: true }).click();
  await page.screenshot({ path: test.info().outputPath("employee-initial.png") });
  expect(await page.locator('.vibe-workspace').evaluate((e) => getComputedStyle(e).backgroundColor)).toBe("rgb(255, 255, 255)");
  await expect(page.getByRole("grid")).toContainText("2021-01-02");
  await expect(page.locator('.ag-header-cell[col-id="password"]')).toHaveCount(0);
  await page.getByRole("button", { name: "열 보기", exact: true }).click();
  await page.getByRole("menuitemcheckbox", { name: "로그인 ID", exact: true }).click();
  await page.keyboard.press("Escape");
  await expect(page.locator('.ag-header-cell[col-id="login_id"]')).toBeVisible();
  await page.getByRole("button", { name: "김서준 상세 보기", exact: true }).click();
  await expect(page.getByRole("dialog", { name: "사원 상세" })).toContainText("person1@example.test");
  await page.screenshot({ path: test.info().outputPath("employee-detail.png") });
  await page.getByRole("button", { name: "닫기", exact: true }).click();
  await firstCheck(page).check();
  await expect(page.getByRole("button", { name: "저장", exact: true })).toBeDisabled();
  await page.getByRole("button", { name: "선택 삭제", exact: true }).click();
  await page.getByRole("button", { name: "취소", exact: true }).click();
  expect(await (await request.get("http://127.0.0.1:3101/__employee-writes")).json()).toEqual([]);
  await page.getByRole("button", { name: "선택 삭제", exact: true }).click();
  await page.getByRole("button", { name: "삭제 표시", exact: true }).click();
  await expect(page.getByRole("button", { name: "변경 1건 저장", exact: true })).toBeEnabled();
  await page.getByRole("button", { name: "삭제 취소", exact: true }).click();
  await expect(page.getByRole("button", { name: "저장", exact: true })).toBeDisabled();
  await nameCell(page).click();
  await expect(page.locator('.ag-cell-inline-editing')).toHaveCount(0);
  await nameCell(page).dblclick();
  await page.locator('.ag-cell-inline-editing input').fill("김서준수정");
  await page.keyboard.press("Enter");
  await page.getByRole("button", { name: "변경 1건 저장", exact: true }).click();
  await expect(page.getByRole("status").filter({ hasText: "테스트 저장 실패" })).toBeVisible();
  await expect(nameCell(page)).toContainText("김서준수정");
  await page.getByRole("button", { name: "변경 1건 저장", exact: true }).click();
  await expect(page.getByRole("status").filter({ hasText: "저장 완료:" })).toBeVisible();
  const writes = await (await request.get("http://127.0.0.1:3101/__employee-writes")).json();
  expect(writes).toHaveLength(2);
  expect(writes[1].update[0].display_name).toBe("김서준수정");
  expect(writes[1].update[0].hire_date).toBe("2021-01-02");
  expect(writes[1].delete).toEqual([]);
  await page.getByRole("button", { name: "입력", exact: true }).click();
  await page.getByRole("button", { name: "변경 1건 저장", exact: true }).click();
  await expect(page.getByRole("status").filter({ hasText: "신규 사원:" })).toBeVisible();
  expect(await (await request.get("http://127.0.0.1:3101/__employee-writes")).json()).toHaveLength(2);
  await page.getByPlaceholder("이름", { exact: true }).fill("이하은");
  await page.getByRole("button", { name: "조회", exact: true }).click();
  await expect(page.getByRole("dialog")).toContainText("저장되지 않은 변경 사항");
  await page.getByRole("button", { name: "무시하고 이동", exact: true }).click();
  await expect(page.getByRole("grid")).toContainText("이하은");
  await expect(page.locator('.ag-center-cols-container [role="row"]')).toHaveCount(1);
  await page.getByRole("button", { name: "조건 초기화", exact: true }).click();
  await expect(page.locator('.ag-center-cols-container [role="row"]')).toHaveCount(3);
  await page.screenshot({ path: test.info().outputPath("employee-workspace.png") });
});

test("mobile navigation search, pins and read-only actions respect allowed menus", async ({ page, request }) => {
  await request.post("http://127.0.0.1:3101/__scenario", { data: { scenario: "employee-ux-no-save" } });
  await page.setViewportSize({ width: 390, height: 844 });
  await login(page);
  await expect(page.getByRole("button", { name: "저장", exact: true })).toHaveCount(0);
  await firstCheck(page).check();
  await expect(page.getByRole("button", { name: "선택 삭제", exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "상세 검색", exact: true }).click();
  await expect(page.getByLabel("계정 사용 여부", { exact: true })).toBeVisible();
  await page.keyboard.press("Control+k");
  const dialog = page.getByRole("dialog", { name: "빠른 이동" });
  await expect(dialog).toBeVisible();
  await dialog.getByLabel("메뉴 또는 열린 탭 검색").fill("사원관리");
  await dialog.getByRole("button", { name: "사원관리 고정", exact: true }).click();
  await expect(dialog.getByRole("button", { name: "사원관리 고정", exact: true })).toHaveAttribute("aria-pressed", "true");
  await dialog.getByRole("button", { name: "열린 탭", exact: true }).click();
  await expect(dialog.getByRole("list", { name: "이동할 메뉴" })).toContainText("사원관리");
  await dialog.getByLabel("메뉴 또는 열린 탭 검색").fill("없는메뉴");
  await expect(dialog.getByText("검색 결과가 없습니다.")).toBeVisible();
  await page.keyboard.press("Escape");
  await page.reload();
  await page.keyboard.press("Control+k");
  await expect(page.getByRole("dialog", { name: "빠른 이동" }).getByRole("button", { name: "사원관리 고정", exact: true })).toHaveAttribute("aria-pressed", "true");
  await page.getByRole("dialog", { name: "빠른 이동" }).getByLabel("메뉴 또는 열린 탭 검색").fill("사원관리");
  await page.keyboard.press("ArrowDown");
  await expect(page.locator('[data-destination="/hr/employee"]')).toBeFocused();
  await page.keyboard.press("Enter");
  await expect(page.getByRole("dialog", { name: "빠른 이동" })).toBeHidden();
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
  await page.screenshot({ path: test.info().outputPath("employee-mobile.png") });
  await page.keyboard.press("Control+k");
  await page.getByRole("dialog", { name: "빠른 이동" }).getByLabel("메뉴 또는 열린 탭 검색").fill("고객사관리");
  await page.keyboard.press("Enter");
  await expect(page).toHaveURL(/\/mng\/companies$/);
  expect(await (await request.get("http://127.0.0.1:3101/__employee-writes")).json()).toEqual([]);
});
