import type { TraScreenConfig } from "@/types/tra";

export const TRA_SCREEN_CONFIGS: Record<string, TraScreenConfig> = {
  "course-events": {
    title: "TRA Course/Event Management",
    resource: "events",
    searchFields: [
      { key: "event_code", placeholder: "Event code" },
      { key: "event_name", placeholder: "Event name" },
      { key: "course_id", placeholder: "Course ID" },
    ],
    columns: [
      { field: "course_id", headerName: "Course ID", type: "number", minWidth: 110, required: true },
      { field: "event_code", headerName: "Event Code", minWidth: 130, required: true },
      { field: "event_name", headerName: "Event Name", minWidth: 200, flex: 1, required: true },
      { field: "start_date", headerName: "Start Date", type: "date", minWidth: 120 },
      { field: "end_date", headerName: "End Date", type: "date", minWidth: 120 },
      { field: "edu_hour", headerName: "Hours", type: "number", minWidth: 90 },
      { field: "status_code", headerName: "Status", minWidth: 100 },
      { field: "max_person", headerName: "Capacity", type: "number", minWidth: 90 },
      { field: "is_active", headerName: "Active", type: "boolean", width: 80 },
    ],
    defaultRow: {
      course_id: null,
      event_code: "",
      event_name: "",
      start_date: null,
      end_date: null,
      edu_hour: 0,
      status_code: "open",
      max_person: 0,
      is_active: true,
    },
  },
  applications: {
    title: "TRA Application Management",
    resource: "applications",
    searchFields: [
      { key: "application_no", placeholder: "Application no" },
      { key: "employee_id", placeholder: "Employee ID" },
      { key: "status", placeholder: "Status" },
    ],
    columns: [
      { field: "application_no", headerName: "Application No", minWidth: 160 },
      { field: "employee_id", headerName: "Employee ID", type: "number", minWidth: 110, required: true },
      { field: "course_id", headerName: "Course ID", type: "number", minWidth: 100, required: true },
      { field: "event_id", headerName: "Event ID", type: "number", minWidth: 100 },
      { field: "status", headerName: "Status", minWidth: 120 },
      { field: "year_plan_yn", headerName: "Year Plan", type: "boolean", width: 100 },
      { field: "survey_yn", headerName: "Survey", type: "boolean", width: 90 },
      { field: "note", headerName: "Note", minWidth: 200, flex: 1 },
    ],
    defaultRow: {
      application_no: "",
      employee_id: null,
      course_id: null,
      event_id: null,
      status: "draft",
      year_plan_yn: false,
      survey_yn: false,
      note: "",
    },
  },
  "required-standards": {
    title: "TRA Required Rule Management",
    resource: "required-standards",
    searchFields: [
      { key: "year", placeholder: "Year" },
      { key: "rule_code", placeholder: "Rule code" },
      { key: "course_id", placeholder: "Course ID" },
    ],
    columns: [
      { field: "year", headerName: "Year", type: "number", minWidth: 90, required: true },
      { field: "rule_code", headerName: "Rule Code", minWidth: 110, required: true },
      { field: "order_seq", headerName: "Order", type: "number", minWidth: 90 },
      { field: "course_id", headerName: "Course ID", type: "number", minWidth: 100, required: true },
      { field: "entry_month", headerName: "Entry Month", type: "number", minWidth: 100 },
      { field: "start_month", headerName: "Start Month", type: "number", minWidth: 100 },
      { field: "end_month", headerName: "End Month", type: "number", minWidth: 100 },
      { field: "edu_level", headerName: "Level", minWidth: 100 },
      { field: "is_active", headerName: "Active", type: "boolean", width: 80 },
    ],
    defaultRow: {
      year: new Date().getFullYear(),
      rule_code: "",
      order_seq: 1,
      course_id: null,
      entry_month: 1,
      start_month: 1,
      end_month: 12,
      edu_level: "",
      is_active: true,
    },
  },
  "required-targets": {
    title: "TRA Required Target Management",
    resource: "required-targets",
    searchFields: [
      { key: "year", placeholder: "Year" },
      { key: "employee_id", placeholder: "Employee ID" },
      { key: "completion_status", placeholder: "Completion status" },
    ],
    columns: [
      { field: "year", headerName: "Year", type: "number", minWidth: 90, required: true },
      { field: "employee_id", headerName: "Employee ID", type: "number", minWidth: 110, required: true },
      { field: "rule_code", headerName: "Rule Code", minWidth: 110, required: true },
      { field: "course_id", headerName: "Course ID", type: "number", minWidth: 100, required: true },
      { field: "edu_month", headerName: "Edu Month", minWidth: 110, required: true },
      { field: "event_id", headerName: "Event ID", type: "number", minWidth: 100 },
      { field: "completion_status", headerName: "Completion", minWidth: 120 },
      { field: "completed_count", headerName: "Completed Cnt", type: "number", minWidth: 120 },
      { field: "note", headerName: "Note", minWidth: 180, flex: 1 },
    ],
    defaultRow: {
      year: new Date().getFullYear(),
      employee_id: null,
      rule_code: "",
      course_id: null,
      edu_month: "",
      event_id: null,
      completion_status: "pending",
      completed_count: 0,
      note: "",
    },
  },
  "elearning-windows": {
    title: "TRA E-learning Window Management",
    resource: "elearning-windows",
    searchFields: [
      { key: "year_month", placeholder: "Year month (YYYYMM)" },
      { key: "start_date", placeholder: "Start date" },
      { key: "end_date", placeholder: "End date" },
    ],
    columns: [
      { field: "year_month", headerName: "Year Month", minWidth: 120, required: true },
      { field: "start_date", headerName: "Start Date", type: "date", minWidth: 120, required: true },
      { field: "end_date", headerName: "End Date", type: "date", minWidth: 120, required: true },
      { field: "app_count", headerName: "Apply Count", type: "number", minWidth: 120 },
      { field: "note", headerName: "Note", minWidth: 220, flex: 1 },
    ],
    defaultRow: {
      year_month: "",
      start_date: null,
      end_date: null,
      app_count: 2,
      note: "",
    },
  },
  histories: {
    title: "TRA History Management",
    resource: "histories",
    searchFields: [
      { key: "employee_id", placeholder: "Employee ID" },
      { key: "course_id", placeholder: "Course ID" },
      { key: "confirm_type", placeholder: "Confirm type (1/0)" },
    ],
    columns: [
      { field: "employee_id", headerName: "Employee ID", type: "number", minWidth: 110, required: true },
      { field: "course_id", headerName: "Course ID", type: "number", minWidth: 100, required: true },
      { field: "event_id", headerName: "Event ID", type: "number", minWidth: 100 },
      { field: "confirm_type", headerName: "Confirm", minWidth: 90 },
      { field: "completed_at", headerName: "Completed At", type: "date", minWidth: 120 },
      { field: "app_point", headerName: "Point", type: "number", minWidth: 100 },
      { field: "unconfirm_reason", headerName: "Unconfirm Reason", minWidth: 200, flex: 1 },
      { field: "note", headerName: "Note", minWidth: 180, flex: 1 },
    ],
    defaultRow: {
      employee_id: null,
      course_id: null,
      event_id: null,
      confirm_type: "0",
      completed_at: null,
      app_point: 0,
      unconfirm_reason: "",
      note: "",
    },
  },
  "cyber-upload": {
    title: "TRA Cyber Upload Management",
    resource: "cyber-uploads",
    searchFields: [
      { key: "upload_ym", placeholder: "Upload year month (YYYYMM)" },
      { key: "employee_no", placeholder: "Employee no" },
      { key: "course_name", placeholder: "Course name" },
    ],
    columns: [
      { field: "upload_ym", headerName: "Upload YM", minWidth: 120, required: true },
      { field: "employee_no", headerName: "Employee No", minWidth: 120 },
      { field: "course_name", headerName: "Course Name", minWidth: 220, flex: 1, required: true },
      { field: "start_date", headerName: "Start Date", type: "date", minWidth: 120 },
      { field: "end_date", headerName: "End Date", type: "date", minWidth: 120 },
      { field: "edu_hour", headerName: "Edu Hour", type: "number", minWidth: 100 },
      { field: "reward_hour", headerName: "Reward Hour", type: "number", minWidth: 110 },
      { field: "organization_name", headerName: "Organization", minWidth: 150 },
      { field: "confirm_type", headerName: "Confirm", minWidth: 90 },
      { field: "close_yn", headerName: "Closed", type: "boolean", width: 90 },
      { field: "note", headerName: "Note", minWidth: 170, flex: 1 },
    ],
    defaultRow: {
      upload_ym: "",
      employee_no: "",
      course_name: "",
      start_date: null,
      end_date: null,
      edu_hour: 0,
      reward_hour: 0,
      organization_name: "",
      confirm_type: "0",
      close_yn: false,
      note: "",
    },
  },
};
