import type { TraScreenConfig } from "@/types/tra";

export const TRA_SCREEN_CONFIGS: Record<string, TraScreenConfig> = {
  "course-events": {
    title: "TRA 과정/차수 관리",
    resource: "events",
    searchFields: [
      { key: "event_code", placeholder: "차수 코드" },
      { key: "event_name", placeholder: "차수명" },
      { key: "course_id", placeholder: "과정 ID" },
    ],
    columns: [
      { field: "course_id", headerName: "과정 ID", type: "number", minWidth: 110, required: true },
      { field: "event_code", headerName: "차수 코드", minWidth: 130, required: true },
      { field: "event_name", headerName: "차수명", minWidth: 200, flex: 1, required: true },
      { field: "start_date", headerName: "시작일", type: "date", minWidth: 120 },
      { field: "end_date", headerName: "종료일", type: "date", minWidth: 120 },
      { field: "edu_hour", headerName: "교육시간", type: "number", minWidth: 90 },
      { field: "status_code", headerName: "상태", minWidth: 100 },
      { field: "max_person", headerName: "정원", type: "number", minWidth: 90 },
      { field: "is_active", headerName: "사용", type: "boolean", width: 80 },
    ],
    defaultRow: {
      course_id: null,
      event_code: "",
      event_name: "",
      start_date: null,
      end_date: null,
      edu_hour: 0,
      status_code: "open",
      max_person: 0,
      is_active: true,
    },
  },
  applications: {
    title: "TRA 교육신청 관리",
    resource: "applications",
    searchFields: [
      { key: "application_no", placeholder: "신청번호" },
      { key: "employee_id", placeholder: "사번 ID" },
      { key: "status", placeholder: "상태" },
    ],
    columns: [
      { field: "application_no", headerName: "신청번호", minWidth: 160 },
      { field: "employee_id", headerName: "사번 ID", type: "number", minWidth: 110, required: true },
      { field: "course_id", headerName: "과정 ID", type: "number", minWidth: 100, required: true },
      { field: "event_id", headerName: "차수 ID", type: "number", minWidth: 100 },
      { field: "status", headerName: "상태", minWidth: 120 },
      { field: "year_plan_yn", headerName: "연간계획", type: "boolean", width: 100 },
      { field: "survey_yn", headerName: "설문", type: "boolean", width: 90 },
      { field: "note", headerName: "비고", minWidth: 200, flex: 1 },
    ],
    defaultRow: {
      application_no: "",
      employee_id: null,
      course_id: null,
      event_id: null,
      status: "draft",
      year_plan_yn: false,
      survey_yn: false,
      note: "",
    },
  },
  "required-standards": {
    title: "TRA 필수교육 기준관리",
    resource: "required-standards",
    searchFields: [
      { key: "year", placeholder: "연도" },
      { key: "rule_code", placeholder: "기준 코드" },
      { key: "course_id", placeholder: "과정 ID" },
    ],
    columns: [
      { field: "year", headerName: "연도", type: "number", minWidth: 90, required: true },
      { field: "rule_code", headerName: "기준 코드", minWidth: 110, required: true },
      { field: "order_seq", headerName: "순번", type: "number", minWidth: 90 },
      { field: "course_id", headerName: "과정 ID", type: "number", minWidth: 100, required: true },
      { field: "entry_month", headerName: "입사월", type: "number", minWidth: 100 },
      { field: "start_month", headerName: "시작월", type: "number", minWidth: 100 },
      { field: "end_month", headerName: "종료월", type: "number", minWidth: 100 },
      { field: "edu_level", headerName: "교육등급", minWidth: 100 },
      { field: "is_active", headerName: "사용", type: "boolean", width: 80 },
    ],
    defaultRow: {
      year: new Date().getFullYear(),
      rule_code: "",
      order_seq: 1,
      course_id: null,
      entry_month: 1,
      start_month: 1,
      end_month: 12,
      edu_level: "",
      is_active: true,
    },
  },
  "required-targets": {
    title: "TRA 필수교육 대상관리",
    resource: "required-targets",
    searchFields: [
      { key: "year", placeholder: "연도" },
      { key: "employee_id", placeholder: "사번 ID" },
      { key: "completion_status", placeholder: "이수상태" },
    ],
    columns: [
      { field: "year", headerName: "연도", type: "number", minWidth: 90, required: true },
      { field: "employee_id", headerName: "사번 ID", type: "number", minWidth: 110, required: true },
      { field: "rule_code", headerName: "기준 코드", minWidth: 110, required: true },
      { field: "course_id", headerName: "과정 ID", type: "number", minWidth: 100, required: true },
      { field: "edu_month", headerName: "교육월", minWidth: 110, required: true },
      { field: "event_id", headerName: "차수 ID", type: "number", minWidth: 100 },
      { field: "completion_status", headerName: "이수여부", minWidth: 120 },
      { field: "completed_count", headerName: "이수횟수", type: "number", minWidth: 120 },
      { field: "note", headerName: "비고", minWidth: 180, flex: 1 },
    ],
    defaultRow: {
      year: new Date().getFullYear(),
      employee_id: null,
      rule_code: "",
      course_id: null,
      edu_month: "",
      event_id: null,
      completion_status: "pending",
      completed_count: 0,
      note: "",
    },
  },
  "elearning-windows": {
    title: "TRA 이러닝 신청기간 관리",
    resource: "elearning-windows",
    searchFields: [
      { key: "year_month", placeholder: "년월 (YYYYMM)" },
      { key: "start_date", placeholder: "시작일" },
      { key: "end_date", placeholder: "종료일" },
    ],
    columns: [
      { field: "year_month", headerName: "년월", minWidth: 120, required: true },
      { field: "start_date", headerName: "시작일", type: "date", minWidth: 120, required: true },
      { field: "end_date", headerName: "종료일", type: "date", minWidth: 120, required: true },
      { field: "app_count", headerName: "신청횟수", type: "number", minWidth: 120 },
      { field: "note", headerName: "비고", minWidth: 220, flex: 1 },
    ],
    defaultRow: {
      year_month: "",
      start_date: null,
      end_date: null,
      app_count: 2,
      note: "",
    },
  },
  histories: {
    title: "TRA 이수이력 관리",
    resource: "histories",
    searchFields: [
      { key: "employee_id", placeholder: "사번 ID" },
      { key: "course_id", placeholder: "과정 ID" },
      { key: "confirm_type", placeholder: "확정구분 (1/0)" },
    ],
    columns: [
      { field: "employee_id", headerName: "사번 ID", type: "number", minWidth: 110, required: true },
      { field: "course_id", headerName: "과정 ID", type: "number", minWidth: 100, required: true },
      { field: "event_id", headerName: "차수 ID", type: "number", minWidth: 100 },
      { field: "confirm_type", headerName: "확정", minWidth: 90 },
      { field: "completed_at", headerName: "이수일시", type: "date", minWidth: 120 },
      { field: "app_point", headerName: "점수", type: "number", minWidth: 100 },
      { field: "unconfirm_reason", headerName: "미확정 사유", minWidth: 200, flex: 1 },
      { field: "note", headerName: "비고", minWidth: 180, flex: 1 },
    ],
    defaultRow: {
      employee_id: null,
      course_id: null,
      event_id: null,
      confirm_type: "0",
      completed_at: null,
      app_point: 0,
      unconfirm_reason: "",
      note: "",
    },
  },
  "cyber-upload": {
    title: "TRA 사이버 업로드 관리",
    resource: "cyber-uploads",
    searchFields: [
      { key: "upload_ym", placeholder: "업로드 년월 (YYYYMM)" },
      { key: "employee_no", placeholder: "사번" },
      { key: "course_name", placeholder: "과정명" },
    ],
    columns: [
      { field: "upload_ym", headerName: "업로드년월", minWidth: 120, required: true },
      { field: "employee_no", headerName: "사번", minWidth: 120 },
      { field: "course_name", headerName: "과정명", minWidth: 220, flex: 1, required: true },
      { field: "start_date", headerName: "시작일", type: "date", minWidth: 120 },
      { field: "end_date", headerName: "종료일", type: "date", minWidth: 120 },
      { field: "edu_hour", headerName: "교육시간", type: "number", minWidth: 100 },
      { field: "reward_hour", headerName: "인정시간", type: "number", minWidth: 110 },
      { field: "organization_name", headerName: "교육기관", minWidth: 150 },
      { field: "confirm_type", headerName: "확정", minWidth: 90 },
      { field: "close_yn", headerName: "마감", type: "boolean", width: 90 },
      { field: "note", headerName: "비고", minWidth: 170, flex: 1 },
    ],
    defaultRow: {
      upload_ym: "",
      employee_no: "",
      course_name: "",
      start_date: null,
      end_date: null,
      edu_hour: 0,
      reward_hour: 0,
      organization_name: "",
      confirm_type: "0",
      close_yn: false,
      note: "",
    },
  },
};
