"""cleanup: drop legacy users table, dedupe auth index, align calculated_at and PAP index names

Revision ID: 75d1c0e7dd53
Revises: 46507f02680a
Create Date: 2026-07-09 11:50:57.581870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75d1c0e7dd53'
down_revision: Union[str, Sequence[str], None] = '46507f02680a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index(op.f('ix_pap_appraisal_masters_appraisal_code'), table_name='PAP_APPRAISAL_MASTERS')
    op.drop_index(op.f('ix_pap_appraisal_masters_appraisal_year'), table_name='PAP_APPRAISAL_MASTERS')
    op.create_index(op.f('ix_PAP_APPRAISAL_MASTERS_appraisal_code'), 'PAP_APPRAISAL_MASTERS', ['appraisal_code'], unique=False)
    op.create_index(op.f('ix_PAP_APPRAISAL_MASTERS_appraisal_year'), 'PAP_APPRAISAL_MASTERS', ['appraisal_year'], unique=False)
    op.drop_index(op.f('ux_auth_users_login_id'), table_name='auth_users')
    op.alter_column('tim_attendance_daily', 'calculated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tim_attendance_daily', 'calculated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ux_auth_users_login_id'), 'auth_users', ['login_id'], unique=True)
    op.drop_index(op.f('ix_PAP_APPRAISAL_MASTERS_appraisal_year'), table_name='PAP_APPRAISAL_MASTERS')
    op.drop_index(op.f('ix_PAP_APPRAISAL_MASTERS_appraisal_code'), table_name='PAP_APPRAISAL_MASTERS')
    op.create_index(op.f('ix_pap_appraisal_masters_appraisal_year'), 'PAP_APPRAISAL_MASTERS', ['appraisal_year'], unique=False)
    op.create_index(op.f('ix_pap_appraisal_masters_appraisal_code'), 'PAP_APPRAISAL_MASTERS', ['appraisal_code'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('username', name=op.f('users_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
