"""add gl accounts mappings vouchers and voucher lines

Revision ID: 7e248ebed919
Revises: 470095da5995
Create Date: 2026-07-09 10:25:16.738868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7e248ebed919'
down_revision: Union[str, Sequence[str], None] = '470095da5995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gl_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('account_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('is_net_pay_account', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_gl_accounts_code')
    )
    op.create_index(op.f('ix_gl_accounts_code'), 'gl_accounts', ['code'], unique=False)
    op.create_table('pay_gl_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pay_item_code', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('gl_account_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gl_account_code'], ['gl_accounts.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pay_item_code', 'effective_from', name='uq_pay_gl_mappings_item_period')
    )
    op.create_index(op.f('ix_pay_gl_mappings_effective_from'), 'pay_gl_mappings', ['effective_from'], unique=False)
    op.create_index(op.f('ix_pay_gl_mappings_gl_account_code'), 'pay_gl_mappings', ['gl_account_code'], unique=False)
    op.create_index('ix_pay_gl_mappings_item_code', 'pay_gl_mappings', ['pay_item_code'], unique=False)
    op.create_table('pay_vouchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher_no', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('voucher_date', sa.Date(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('total_debit', sa.Float(), nullable=False),
    sa.Column('total_credit', sa.Float(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['pay_payroll_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', name='uq_pay_vouchers_run_id'),
    sa.UniqueConstraint('voucher_no', name='uq_pay_vouchers_voucher_no')
    )
    op.create_index(op.f('ix_pay_vouchers_run_id'), 'pay_vouchers', ['run_id'], unique=False)
    op.create_index(op.f('ix_pay_vouchers_voucher_date'), 'pay_vouchers', ['voucher_date'], unique=False)
    op.create_index(op.f('ix_pay_vouchers_voucher_no'), 'pay_vouchers', ['voucher_no'], unique=False)
    op.create_table('pay_voucher_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('gl_account_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('cost_center_code', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('debit_amount', sa.Float(), nullable=False),
    sa.Column('credit_amount', sa.Float(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('source_item_code', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gl_account_code'], ['gl_accounts.code'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['pay_vouchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pay_voucher_lines_gl_account_code'), 'pay_voucher_lines', ['gl_account_code'], unique=False)
    op.create_index('ix_pay_voucher_lines_voucher', 'pay_voucher_lines', ['voucher_id', 'line_no'], unique=False)
    op.create_index(op.f('ix_pay_voucher_lines_voucher_id'), 'pay_voucher_lines', ['voucher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pay_voucher_lines_voucher_id'), table_name='pay_voucher_lines')
    op.drop_index('ix_pay_voucher_lines_voucher', table_name='pay_voucher_lines')
    op.drop_index(op.f('ix_pay_voucher_lines_gl_account_code'), table_name='pay_voucher_lines')
    op.drop_table('pay_voucher_lines')
    op.drop_index(op.f('ix_pay_vouchers_voucher_no'), table_name='pay_vouchers')
    op.drop_index(op.f('ix_pay_vouchers_voucher_date'), table_name='pay_vouchers')
    op.drop_index(op.f('ix_pay_vouchers_run_id'), table_name='pay_vouchers')
    op.drop_table('pay_vouchers')
    op.drop_index('ix_pay_gl_mappings_item_code', table_name='pay_gl_mappings')
    op.drop_index(op.f('ix_pay_gl_mappings_gl_account_code'), table_name='pay_gl_mappings')
    op.drop_index(op.f('ix_pay_gl_mappings_effective_from'), table_name='pay_gl_mappings')
    op.drop_table('pay_gl_mappings')
    op.drop_index(op.f('ix_gl_accounts_code'), table_name='gl_accounts')
    op.drop_table('gl_accounts')
    # ### end Alembic commands ###
