"""add severance phase2 tax columns

Revision ID: ea501237b804
Revises: ffc17a622333
Create Date: 2026-07-09 15:56:45.301835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ea501237b804'
down_revision: Union[str, Sequence[str], None] = 'ffc17a622333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr_severance_calcs', sa.Column('service_years', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('hr_severance_calcs', sa.Column('income_tax', sa.Float(), nullable=False, server_default='0'))
    op.add_column('hr_severance_calcs', sa.Column('local_income_tax', sa.Float(), nullable=False, server_default='0'))
    op.add_column('hr_severance_calcs', sa.Column('net_severance', sa.Float(), nullable=False, server_default='0'))
    op.add_column('hr_severance_calcs', sa.Column('tax_detail_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('hr_severance_calcs', 'service_years', server_default=None)
    op.alter_column('hr_severance_calcs', 'income_tax', server_default=None)
    op.alter_column('hr_severance_calcs', 'local_income_tax', server_default=None)
    op.alter_column('hr_severance_calcs', 'net_severance', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hr_severance_calcs', 'tax_detail_json')
    op.drop_column('hr_severance_calcs', 'net_severance')
    op.drop_column('hr_severance_calcs', 'local_income_tax')
    op.drop_column('hr_severance_calcs', 'income_tax')
    op.drop_column('hr_severance_calcs', 'service_years')
    # ### end Alembic commands ###
