"""add disbursement voucher type and cash account flag

Revision ID: ffc17a622333
Revises: 75d1c0e7dd53
Create Date: 2026-07-09 15:16:13.921501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ffc17a622333'
down_revision: Union[str, Sequence[str], None] = '75d1c0e7dd53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gl_accounts', sa.Column('is_cash_account', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('pay_vouchers', sa.Column('voucher_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False, server_default='accrual'))
    op.drop_constraint(op.f('uq_pay_vouchers_run_id'), 'pay_vouchers', type_='unique')
    op.create_unique_constraint('uq_pay_vouchers_run_id_voucher_type', 'pay_vouchers', ['run_id', 'voucher_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_pay_vouchers_run_id_voucher_type', 'pay_vouchers', type_='unique')
    op.create_unique_constraint(op.f('uq_pay_vouchers_run_id'), 'pay_vouchers', ['run_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('pay_vouchers', 'voucher_type')
    op.drop_column('gl_accounts', 'is_cash_account')
    # ### end Alembic commands ###
